### ISSUE TITLE
Actions missing in Loupedeck profile for OBS Studio

### ISSUE THREAD

**Issue by Troedson** [Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin#11]
When I start Loupedeck (after having started OBS Studio), I miss the three folders:
![Loupedeck](https://user-images.githubusercontent.com/121905105/210448443-cd016c84-eb44-4672-82d3-b12c78bad176.jpg)
 1. Scenes, 2. Sources and 3. Audio. All I can see is 4. Scene Collections and the following actions, mostly regarding recording and streaming.

If I uninstall, and then reinstall, the profile it works, I can see all folders and all actions. But when I close the app and restart it, most of the actions are invisible again.

OBS version is 28.1.2
Loupdeck is 5.4.1.15259
Profile is OBS Studio 5.4.2

My hardware is a Loupdeck CT

Any solutions?

**Comment by laperie** [comment]
Can you please supply the logs? Please see https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/issues/9 for details.

**Comment by Troedson** [comment]
Good morning!

Here are the logs from yesterdays tries…

All the best

Troed

***@***.***
Troed Troedson
Troed Ventures
m:
+46 705867288<+46%20703%2096%2082%2057>
w:
troedventures.com<http://www.troedventures.com/>  e: ***@***.******@***.***>


Från: Andrei Laperie ***@***.***>
Skickat: den 4 januari 2023 10:08
Till: Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin ***@***.***>
Kopia: Troed Troedson ***@***.***>; Author ***@***.***>
Ämne: Re: [Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin] Actions missing in Loupedeck profile for OBS Studio (Issue #11)


Can you please supply the logs? Please see #9<https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/issues/9> for details.

**Comment by laperie** [comment]
> Good morning!
> Here are the logs from yesterdays tries…
> All the best

I am afraid the logs are not attached, at least I cannot see them. Can you please try uploading zip with logs again?

**Comment by Troedson** [comment]
New try...


[Loupedecklogs 220103.zip](https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/files/10343409/Loupedecklogs.220103.zip)

**Comment by laperie** [comment]
> New try...
> 
That's much better ;) however,  please give me another version collected using this instruction: https://support.loupedeck.com/loupedeck-logs-collection

Apologies I was not clear enough in my earlier message

**Comment by laperie** [comment]
I still can't see any logs, @Troedson , if you can reproduce the behavior with the recent OBS plugin from the marketplace, please add the logs as I was describing above.

**Comment by Troedson** [comment]
Hello Andrei!

I’m  sorry I didn’t get back to you, I’ve been traveling and not in my studio for some days. I’m gonna reinstall everything next week and see if the problem persists. If so, I’ll get back to you.

Thanks a lot for now!

Troed


***@***.***
Troed Troedson
Troed Ventures
m:
+46 705867288<+46%20703%2096%2082%2057>
w:
troedventures.com<http://www.troedventures.com/>  e: ***@***.******@***.***>


Från: Andrei Laperie ***@***.***>
Skickat: den 10 januari 2023 22:16
Till: Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin ***@***.***>
Kopia: Troed Troedson ***@***.***>; Mention ***@***.***>
Ämne: Re: [Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin] Actions missing in Loupedeck profile for OBS Studio (Issue #11)


I still can't see any logs, @Troedson<https://github.com/Troedson> , if you can reproduce the behavior with the recent OBS plugin from the marketplace, please add the logs as I was describing above.

**Comment by yaeda** [comment]
I have the same trouble, and I found another strange behavior.

reproduce step
1. Launch OBS
2. Launch Loupedeck -> missing 1,2,3 folders
3. Add a source in OBS (like Text or Image)
4. "2. Sources" is shown in Loupdeck (but it has only a source that I added above)

OBS version is 29.0.0
Loupdeck is 5.4.1.15260
OBS Studio 5.4.2
My hardware is a Loupdeck Live S

**Comment by laperie** [comment]
Hi @yaeda ,  
if at all possible, please provide the logs  -- I believe that there is an unhandled exception somewhere that prevents the gathering of the scenes. With the logs, I believe I can fix that. [Here](https://support.loupedeck.com/loupedeck-logs-collection) is how to collect them.

> I have the same trouble, and I found another strange behavior.
> 
> reproduce step
> 
> 1. Launch OBS
> 2. Launch Loupedeck -> missing 1,2,3 folders
> 3. Add a source in OBS (like Text or Image)
> 4. "2. Sources" is shown in Loupdeck (but it has only a source that I added above)
> 
> OBS version is 29.0.0 Loupdeck is 5.4.1.15260 OBS Studio 5.4.2 My hardware is a Loupdeck Live S

**Comment by yaeda** [comment]
@laperie Thanks for your quick reply.
However,, I stopped the Loopedeck application from the menu bar icon and restart it again, then solved the problem.
I will send you a log when I face this issue again.

**Comment by laperie** [comment]
(hopefully) Fixed in release 5.4.20006
