### ISSUE TITLE
Audio scène in OBS skip to -40 DB to -INF 

### ISSUE THREAD

**Issue by Spriingy** [Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin#8]
i use Spotify music a -55 DB but the Loupedeck Fader go to -40DB to -INF, do you think it's possible to start the rotate fader to -INF to 100% Volume 

thanks !

**Comment by 145Micah** [comment]
This would be incredibly helpful please

**Comment by laperie** [comment]
Fixed in release 5.4.20010

**Comment by 145Micah** [comment]
Thank you for letting me know. Excited to test it out. Thank you 🙏

**Comment by 145Micah** [comment]
Hi. At the moment when rotating the fader on an audio scan it is still jumping from -inf to -40db and I am on latest OBS 29.0.2 and Loupedeck OBS Plugin v5.4.2.20004.

Thank you for your help

**Comment by Spriingy** [comment]
U need to download the new pre realease 


https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/releases/tag/5.4.2.20010

**Comment by laperie** [comment]
Up-to-date version of the plugin is available with Loupedeck 5.6 release. Please upgrade
